package debug

import (
	"github.com/bazelbuild/bazel-gazelle/rule"
)

// Kinds returns a map of maps rule names (kinds) and information on how to
// match and merge attributes that may be found in rules of those kinds. All
// kinds of rules generated for this language may be found here.
func (*debugLang) Kinds() map[string]rule.KindInfo {
	return map[string]rule.KindInfo{
		"fake": {
			ResolveAttrs: map[string]bool{"deos": true},
		},
	}
}

// Loads returns .bzl files and symbols they define. Every rule generated by
// GenerateRules, now or in the past, should be loadable from one of these
// files.
func (*debugLang) Loads() []rule.LoadInfo {
	return []rule.LoadInfo{
		{
			Name:    "@this//does/not:exist",
			Symbols: []string{"fake"},
		},
	}
}
