package debug

import (
	"time"

	"github.com/bazelbuild/bazel-gazelle/language"
)

// DebugLangName is the name if this extension.  It is public in case someone
// wanted to refer to it formally.
const DebugLangName = "debug"

// NewLanguage initializes a new extension satisfies the language.Language
// interface. This is the entrypoint for the extension initialization.
func NewLanguage() language.Language {
	return &debugLang{}
}

// debugLang implements language.Language.
type debugLang struct {
	// start marks the time when the RegisterFlags function was called.
	start time.Time
	// prev marks the time when the previous GenerateRules function was called.
	prev time.Time
}

// Name returns the name of the language. This should be a prefix of the kinds
// of rules generated by the language, e.g., "go" for the Go extension since it
// generates "go_library" rules.
func (d *debugLang) Name() string { return DebugLangName }
