package debug

import (
	"time"

	"github.com/bazelbuild/bazel-gazelle/language"
	"github.com/vbauerster/mpb/v7"
)

const DebugLangName = "debug"

// NewLanguage initializes a new extension satisfies the language.Language
// interface. This is the entrypoint for the extension initialization.
func NewLanguage() language.Language {
	return &debugLang{}
}

// debugLang implements language.Language.
type debugLang struct {
	start    time.Time
	prev     time.Time
	progress *mpb.Progress
}

// Name returns the name of the language. This should be a prefix of the kinds
// of rules generated by the language, e.g., "go" for the Go extension since it
// generates "go_library" rules.
func (d *debugLang) Name() string { return DebugLangName }
